### ISSUE TITLE
Feature: User can search for medications

### ISSUE THREAD

**Issue by tam-n** [tam-n/RxTracker#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can type into input to search for medications.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can type into a search bar to find medications from the openFDA API. When the user clicks submit the top 5 results that matches the user's input will be displayed. When no medications are found that matches the user's input, a message will say that no medications were found. When the user clicks the left side drawer component, They can add lists to their account. When the user goes to the medication information page, they can add medications and their dosage, route, and frequency to a selected list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/tam-n/RxTracker/assets/131913803/99125b2e-12ea-40e3-81c8-19414cd58260)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` using the exported DB Design file
- [ ] Update `data.sql` to insert starting data for testing later.

### ⚡ Client Tasks

- [ ] Create a static version of the landing page
 - [ ] Create the header and navigation bar to match the Figma (use Tailwind and FontAwesome). 
- [ ] Create a react search component that displays a list of the top 5 search results that matches the user's input.
 - [ ] As the user types, an API request will be sent to the openFDA API to query for generic or brand medication names that match the user's input 

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
